export const possibleLocation = ["At House Desk Upon Adjournment",
"At Senate Desk Upon Adjournment",
"At Speakers Desk Upon Adjournment",
"Chapter Number Assigned",
"Filed with Secretary of State",
"Governors Office - Awaiting Signature",
"House Desk - Failed",
"In House Committee",
"In House Committee Awaiting transfer to Desk",
"In Senate Committee",
"In Senate Committee Awaiting transfer to Desk",
"Secretary of States Office - Chapter Number Assignment",
"Senate - Tabled",
"Senate Desk - Awaiting Second Reading",
"Senate Desk - Failed",
"Senate Presidents Desk - Awaiting Signature",
"Speakers Desk - Awaiting Signature"]
